server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?current_schema=public
    username: postgres
    password: postgres
  liquibase:
    parameters:
      textColumnType: TEXT
    contexts: nonprod