spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    name: userdb
    url: jdbc:h2:mem:userdb;Mode=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver

  liquibase:
    parameters:
      textColumnType: VARCHAR(250)
    contexts: nonprod
  h2:
    console:
      enabled: true
